# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pcie_pin.xdc

# Block Designs: bd/mb_preset/mb_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset || ORIG_REF_NAME==mb_preset} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_timer_0_0/mb_preset_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_timer_0_0 || ORIG_REF_NAME==mb_preset_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_uartlite_0_0/mb_preset_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_uartlite_0_0 || ORIG_REF_NAME==mb_preset_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_iic_0_0/mb_preset_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_iic_0_0 || ORIG_REF_NAME==mb_preset_axi_iic_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_emc_0_0/mb_preset_axi_emc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_emc_0_0 || ORIG_REF_NAME==mb_preset_axi_emc_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_0/mb_preset_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_0 || ORIG_REF_NAME==mb_preset_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_dlmb_v10_0/mb_preset_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_dlmb_v10_0 || ORIG_REF_NAME==mb_preset_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_ilmb_v10_0/mb_preset_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_ilmb_v10_0 || ORIG_REF_NAME==mb_preset_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_dlmb_bram_if_cntlr_0/mb_preset_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_preset_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_ilmb_bram_if_cntlr_0/mb_preset_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_preset_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_lmb_bram_0/mb_preset_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_lmb_bram_0 || ORIG_REF_NAME==mb_preset_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_xbar_0/mb_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_xbar_0 || ORIG_REF_NAME==mb_preset_xbar_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_us_1/mb_preset_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_us_1 || ORIG_REF_NAME==mb_preset_auto_us_1} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_0/mb_preset_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_0 || ORIG_REF_NAME==mb_preset_auto_ds_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_1/mb_preset_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_1 || ORIG_REF_NAME==mb_preset_auto_ds_1} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_pc_0/mb_preset_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_pc_0 || ORIG_REF_NAME==mb_preset_auto_pc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_2/mb_preset_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_2 || ORIG_REF_NAME==mb_preset_auto_ds_2} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_3/mb_preset_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_3 || ORIG_REF_NAME==mb_preset_auto_ds_3} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_4/mb_preset_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_4 || ORIG_REF_NAME==mb_preset_auto_ds_4} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_5/mb_preset_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_5 || ORIG_REF_NAME==mb_preset_auto_ds_5} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_6/mb_preset_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_6 || ORIG_REF_NAME==mb_preset_auto_ds_6} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_7/mb_preset_auto_ds_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_7 || ORIG_REF_NAME==mb_preset_auto_ds_7} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_pc_1/mb_preset_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_pc_1 || ORIG_REF_NAME==mb_preset_auto_pc_1} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_us_0/mb_preset_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_us_0 || ORIG_REF_NAME==mb_preset_auto_us_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_cc_0/mb_preset_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_cc_0 || ORIG_REF_NAME==mb_preset_auto_cc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_cc_1/mb_preset_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_cc_1 || ORIG_REF_NAME==mb_preset_auto_cc_1} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_auto_ds_8/mb_preset_auto_ds_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_auto_ds_8 || ORIG_REF_NAME==mb_preset_auto_ds_8} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_axi_periph_0/mb_preset_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_preset_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_axi_intc_0/mb_preset_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_preset_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_xlconcat_0/mb_preset_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_preset_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_mdm_1_0 || ORIG_REF_NAME==mb_preset_mdm_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_clk_wiz_1_0/mb_preset_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_clk_wiz_1_0 || ORIG_REF_NAME==mb_preset_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_rst_clk_wiz_1_100M_0/mb_preset_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_preset_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_0_0/mb_preset_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_0_0 || ORIG_REF_NAME==mb_preset_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_1_0/mb_preset_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_1_0 || ORIG_REF_NAME==mb_preset_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_2_0/mb_preset_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_2_0 || ORIG_REF_NAME==mb_preset_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_pcie_0_0/mb_preset_axi_pcie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_pcie_0_0 || ORIG_REF_NAME==mb_preset_axi_pcie_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_bram_ctrl_0_0/mb_preset_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_preset_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_bram_ctrl_0_bram_0/mb_preset_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==mb_preset_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_smc_0/mb_preset_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_smc_0 || ORIG_REF_NAME==mb_preset_axi_smc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_rst_axi_pcie_0_62M_0/mb_preset_rst_axi_pcie_0_62M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_rst_axi_pcie_0_62M_0 || ORIG_REF_NAME==mb_preset_rst_axi_pcie_0_62M_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_util_ds_buf_0_0/mb_preset_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_util_ds_buf_0_0 || ORIG_REF_NAME==mb_preset_util_ds_buf_0_0} -quiet] -quiet

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV3/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/mb_preset_ooc.xdc
