# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.srcs/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/mb_preset_axi_smc_0.xci
# IP: The module: 'mb_preset_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/bd_9e88.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_0/bd_9e88_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_2/bd_9e88_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_3/bd_9e88_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_4/bd_9e88_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_5/bd_9e88_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_6/bd_9e88_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_7/bd_9e88_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_8/bd_9e88_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_9/bd_9e88_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_10/bd_9e88_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_11/bd_9e88_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_12/bd_9e88_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_5/bd_9e88_s00a2s_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_6/bd_9e88_sarn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_7/bd_9e88_srn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_8/bd_9e88_sawn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_9/bd_9e88_swn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_10/bd_9e88_sbn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_11/bd_9e88_m00s2a_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.srcs/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/mb_preset_axi_smc_0.xci
# IP: The module: 'mb_preset_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/bd_9e88.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_0/bd_9e88_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_2/bd_9e88_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_3/bd_9e88_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_4/bd_9e88_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_5/bd_9e88_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_6/bd_9e88_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_7/bd_9e88_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_8/bd_9e88_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_9/bd_9e88_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_10/bd_9e88_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_11/bd_9e88_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_12/bd_9e88_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_1/bd_9e88_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_5/bd_9e88_s00a2s_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_6/bd_9e88_sarn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_7/bd_9e88_srn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_8/bd_9e88_sawn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_9/bd_9e88_swn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_10/bd_9e88_sbn_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/bd_0/ip/ip_11/bd_9e88_m00s2a_0_ooc.xdc

# XDC: d:/Tony/Downloads/RainbowGhost/Code/mircoBlaze_VC707_PCIeV2/mircoBlaze_VC707_PCIeV2.gen/sources_1/bd/mb_preset/ip/mb_preset_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
